import { RouteInfo } from "../shared/sidebar/sidebar.metadata";

export const ROUTES: RouteInfo[] = [
  {
    path: '',
    title: 'Dashboard',
    icon: 'icon-Car-Wheel',
    class: 'has-arrow',
    permissions: ['ADMIN'],
    extralink: false,
    submenu: [
      {
        path: 'dashboard/dashboard1',
        title: 'Dashboard',
        icon: '',
        class: '',
        permissions: ['ADMIN'],
        extralink: false,
        submenu: []
      },
    ],
  },
  {
    path: '',
    title: 'Gestione',
    icon: 'mdi mdi-dots-horizontal',
    class: 'nav-small-cap',
    extralink: true,
    permissions: [],
    submenu: [],    
  },
  {
    path: '',
    title: 'Utenti',
    icon: 'icon-Administrator',
    class: 'has-arrow',
    extralink: false,
    permissions: [],
    submenu: [
      {
        path: 'users',
        title: 'Utenti',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permissions: ['ADMIN'],
      },
      {
        path: 'roles',
        title: 'Ruoli',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permissions: ['ADMIN'],
      },
      {
        path: 'permissions',
        title: 'Permessi',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permissions: ['ADMIN'], 
      },  
    ]}, //chiude gestione utenti
    {
      path: '',
      title: 'Configurazioni',
      icon: 'icon-Gear',
      class: 'has-arrow',
      extralink: false,
      permissions: [],
      submenu: [  
      {
        path: 'tipopagamenti',
        title: 'Tipo pagamenti',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permissions: ['ADMIN'], 
      },          
      {
        path: 'classificazioni',
        title: 'Classificazione',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permissions: ['ADMIN'], 
      }, 
      {
        path: 'mappinguffici',
        title: 'Mapping uffici',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permissions: ['ADMIN'], 
      }, 
      {
        path: 'tasks',
        title: 'Attività',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permissions: ['ADMIN'], 
      }, 
      {
        path: 'aziendeloc',
        title: 'Aziende',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permissions: ['ADMIN'], 
      },
    ]}, //chiude configurazioni 
    {
    path: '',
    title: 'Ricerche Titulus',
    icon: 'icon-Paint-Brush',
    class: 'has-arrow',
    extralink: false,
    permissions: [],
    submenu: [ 
      {
        path: 'personeinterne',
        title: 'Persone interne',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permissions: ['ADMIN'], 
      }, 
      {
        path: 'struttureinterne',
        title: 'Strutture interne',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permissions: ['ADMIN'], 
      }, 
      {
        path: 'struttureesterne',
        title: 'Strutture esterne',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permissions: ['ADMIN'], 
      }, 
      {
        path: 'documenti',
        title: 'Documenti',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permissions: ['ADMIN'], 
      }, 
    ]},//chiude ricerche titulus
    
  
  {
    path: '',
    title: 'Funzionalità',
    icon: 'mdi mdi-dots-horizontal',
    class: 'nav-small-cap',
    extralink: true,
    permissions: [],
    submenu: [],    
  },    
  {
    path: 'multistep-schematipo',
    title: 'Nuova convenzione',
    icon: 'icon-File',
    class: '',
    extralink: false,
    submenu: [],
    permissions: ['ADMIN'],
  },
  {
    path: 'convenzioni',
    title: 'Convenzioni',
    icon: 'icon-File-Search',
    class: '',
    extralink: false,
    submenu: [],
    permissions: ['ADMIN'],
  },
  {
    path: 'scadenze',
    title: 'Scadenze pagamenti',
    icon: 'icon-File-Search',
    class: '',
    extralink: false,
    submenu: [],
    permissions: ['ADMIN'], 
  }, 
  {
    path: '',
    title: 'Fasi',
    icon: 'icon-Wrench',
    class: 'has-arrow',
    extralink: false,
    permissions: [],
    submenu: [ 
      {
        path: 'validazione',
        title: 'Approvazione',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permissions: ['ADMIN','VALIDATORE'],
      },     
      {
        path: '',
        title: 'Sottoscrizione',
        icon: '',
        class: 'has-arrow',
        extralink: false,        
        permissions: ['ADMIN'],        
        submenu: [  
          {
            path: 'sottoscrizione',
            title: 'Inizio sottoscrizione',
            icon: '',
            class: '',
            extralink: false,        
            permissions: ['ADMIN'],        
            submenu: [],        
          },
          {
            path: 'firmacontroparte',
            title: 'Completa controparte',
            icon: '',
            class: '',
            extralink: false,
            submenu: [],
            permissions: ['ADMIN'],
          },
          {
            path: 'firmadirettore',
            title: 'Completa direttore',
            icon: '',
            class: '',
            extralink: false,
            submenu: [],
            permissions: ['ADMIN'],
          },         
        ],        
      },
      {
        path: 'bollorepertoriazione',
        title: 'Bollo repertoriazione',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permissions: ['ADMIN'],
      },     
      {
        path: 'richiestaemissione',
        title: 'Richiesta emissione',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permissions: ['ADMIN'],
      },    
      {
        path: 'inviorichiestapagamento',
        title: 'Richiesta pagamento',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permissions: ['ADMIN'],
      },     

    ]
  }
];
